import { Inter, Philosopher, Crimson_Pro } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const philosopher = Philosopher({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-philosopher",
});

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  variable: "--font-crimson-pro",
});

export const metadata = {
  title: "IKS Gyan Gunjan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="/js/jquery.min.js"></script>
        <script src="/js/html2canvas.min.js"></script>
        <script src="/js/three.min.js"></script>
        <script src="/js/pdf.min.js"></script>
        <script src="/js/pdf.worker.js"></script>
        <script src="/js/3dflipbook.min.js"></script>
        <link rel="stylesheet" href="/css/custom-flipbook.css" />
      </head>
      <body
        suppressHydrationWarning
        className={`${inter.variable} ${philosopher.variable} ${crimsonPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
